<a href="https://colab.research.google.com/github/FallingFrost/robotics_ebooks/blob/master/Tutorial_One.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## UFMFRR-15-M - Machine Vision Tutorial

# Unit 1 - Python and Google Colab, Grouping

In [1]:
import numpy as np  # import a package (numpy)
import cv2  #  opencv

# !pip list  # list all the packages that have been pre-installed

!python --version  # show python version
print(cv2.__version__)  # show opencv version
print(np.__version__)  #show numpy version

Python 3.13.15
4.14.0
2.1.3


# Test if a GPU is available

In [2]:
!nvidia-smi

Fri Oct  2 08:41:47 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             14W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

# Install a package/library

In [4]:
!pip install keras  # In fact, keras should have been pre-installed in Colab

# Basic data types


In [5]:
x = 5  # int
y = 1.5  # float
z = True  # boolean
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'bool'>


In [6]:
machine = 'machine'
mv = machine + '_' + 'vision'  # concatenation of strings
print(mv)
print(type(mv))

machine_vision
<class 'str'>


* Please refer to some of the [useful string methods](https://docs.python.org/release/3.6.9/library/stdtypes.html#string-methods)

# Lists, Dictionaries, Sets and Tuples

In [7]:
a = [1, 2, 3]
b = ['x', 'y', 'z']
a[1] = 'z'
print(a)
print(b)

[1, 'z', 3]
['x', 'y', 'z']


* More on list [here](https://docs.python.org/release/3.6.9/tutorial/datastructures.html#more-on-lists)
* Read about [Dictionaries](https://docs.python.org/release/3.6.9/library/stdtypes.html#mapping-types-dict), [Sets](https://docs.python.org/release/3.6.9/library/stdtypes.html#set-types-set-frozenset) and [Tuples](https://docs.python.org/release/3.6.9/library/stdtypes.html?highlight=tuple#tuples) yourself

# Numpy

Create a numpy array

In [24]:
a = np.arange(12)
a1 = np.arange(2, 20, 3)  # Return evenly spaced values within a given interval.
b = np.diag(a)  # Extract a diagonal or construct a diagonal array.
print(a)
print(a1)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 2  5  8 11 14 17]
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11]]


Reshape a numpy array

In [25]:
a = a.reshape(3,4)
print(a)
print('The shape of the array is: ' + str(a.shape))
print('The type of the elements: ' + a.dtype.name)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The shape of the array is: (3, 4)
The type of the elements: int64


Add a number to all elements in an array

In [26]:
a = a + 5
print(a)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Slicing

In [27]:
c = a[0:2,2]
print(c)

[ 7 11]


In [30]:
# practice 1
# Initial list of numbers
numbers = [87, 63, 68, 73, 32, 66, 84, 94, 96, 83]

# 1. Create a 10x10 diagonal matrix using a for-loop
A = np.zeros((10, 10), dtype=int)
for i in range(len(numbers)):
    A[i, i] = numbers[i]

# 2. Compute the transpose and matrix product
A_T = A.T
B = np.dot(A, A_T)  # equivalent to A @ A_T

# 3. Compute the trace of the product matrix
trace_result = int(np.trace(B))

print("Trace of the product matrix:", trace_result)

Trace of the product matrix: 58868


In [29]:
# practice 1-instead

numbers = [87, 63, 68, 73, 32, 66, 84, 94, 96, 83]

# Alternative method: Create the diagonal matrix directly using np.diag
A_alt = np.diag(numbers)

# Compute the trace of A @ A.T to verify
trace_alt = int(np.trace(A_alt @ A_alt.T))

print("Trace using alternative method:", trace_alt)

Trace using alternative method: 58868


In [31]:
# practice 2
# 1. Create a 10x10 matrix with all initial values equal to 1
MA = np.ones((10, 10), dtype=int)

# Dictionary of numbers and their (row, col) positions
numbers_positions = {
    98: (0, 1),
    62: (2, 2),
    87: (3, 4),
    35: (5, 1),
    4: (6, 3),
    24: (7, 0),
    28: (1, 5),
    91: (4, 4),
    49: (8, 2),
    100: (9, 9)
}

# 2. Update matrix MA using the dictionary
for val, (r, c) in numbers_positions.items():
    MA[r, c] = val

# 3. Extract submatrix MB (rows 3 to 6, cols 2 to 5)
MB = MA[3:7, 2:6]

# 4. Perform multiplication and sum operations
# Result 1: Multiply all elements in MB
result_1 = np.prod(MB)

# Result 2: Add 10 to each element in MB (matrix MC) and calculate the sum
MC = MB + 10
result_2 = np.sum(MC)

# 5. Calculate the final result
final_result = int(result_1 + result_2)

print("Result 1:", result_1)
print("Result 2:", result_2)
print("Final Result:", final_result)

Result 1: 31668
Result 2: 355
Final Result: 32023


In [32]:
import pandas as pd

# ==========================================
# Step 1: Generate images.csv
# ==========================================

# Define file names (first 5 ascending, next 5 in reverse order)
first_five = ['img_1.jpg', 'img_2.jpg', 'img_3.jpg', 'img_4.jpg', 'img_5.jpg']
file_names = first_five + first_five[::-1]

# Generate values starting from 32, increasing by 2 for each line
values = [32 + 2 * i for i in range(10)]

# Create DataFrame
df = pd.DataFrame({
    'file_name': file_names,
    'value': values
})

# Save to CSV
csv_filename = 'images.csv'
df.to_csv(csv_filename, index=False)
print("CSV file generated successfully.")


# ==========================================
# Step 2: Read CSV and sum specific rows
# ==========================================

# Read CSV back into Python
df_read = pd.read_csv(csv_filename)

# Extract Row 2, Row 7, and Row 8 (0-indexed: index 1, index 6, index 7)
val_row2 = df_read.loc[1, 'value']  # 2nd row -> value: 34
val_row7 = df_read.loc[6, 'value']  # 7th row -> value: 44
val_row8 = df_read.loc[7, 'value']  # 8th row -> value: 46

# Calculate the sum
total_sum = int(val_row2 + val_row7 + val_row8)

print(f"Row 2 value: {val_row2}")
print(f"Row 7 value: {val_row7}")
print(f"Row 8 value: {val_row8}")
print(f"Final Answer (Sum): {total_sum}")

CSV file generated successfully.
Row 2 value: 34
Row 7 value: 44
Row 8 value: 46
Final Answer (Sum): 124


* More on numpy [here](https://numpy.org/doc/1.18/reference/index.html)